---
:concurrency: 5
:queues:
  - [inauthentic_sync, 4]
  - [address_info_updater, 4]
  - [authentic_sync, 3]
  - [transaction_info_updater, 2]
  - [address_cell_consumed_updater, 1]
  - default

production:
  :concurrency: 40
staging:
  :concurrency: 15
