name: Auto merge

on: push

permissions:
  pull-requests: write

jobs:
  merge-develop-into-testnet:
    if: ${{ github.ref == 'refs/heads/develop' }}
    name: Merge develop into testnet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: 'develop'
          destination_branch: 'testnet'
          pr_title: 'Merge develop into testnet'
          pr_reviewer: 'keith-cy'
          pr_label: 'auto-pr'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  merge-testnet-into-mainnet:
    if: ${{ github.ref == 'refs/heads/testnet' }}
    name: Merge testnet into mainnet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: 'testnet'
          destination_branch: 'master'
          pr_title: 'Merge testnet into mainnet'
          pr_reviewer: 'keith-cy'
          pr_label: 'auto-pr'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  merge-mainnet-back-to-develop:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: Merge mainnet back to develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: 'master'
          destination_branch: 'develop'
          pr_title: 'Merge mainnet into develop'
          pr_reviewer: 'keith-cy'
          pr_label: 'auto-pr'
          github_token: ${{ secrets.GITHUB_TOKEN }}
