name: Deploy to mainnet

on: 
  push:
    branches:
      - master
jobs:
  deploy:
    uses: ./.github/workflows/_build_deploy.yml
    with:
      ckb-mode: mainnet
      api-url: $MAINNET_API_URL
      k8s-namespace: mainnet
      k8s-workload: ckb-explorer-front
    secrets: inherit


