name: Deploy to testnet

on: 
  push:
    branches:
      - testnet
jobs:
  deploy:
    uses: ./.github/workflows/_build_deploy.yml
    with:
      ckb-mode: testnet
      api-url: ${{secrets.TESTNET_API_URL}}
      k8s-namespace: testnet
      k8s-workload: ckb-explorer-front
    secrets: inherit

